---
- name: Create a namespace
  hosts: localhost
  become: no
  roles:
    - namespace

# Playbook to deploy Ghost and its components
- name: Database configuration
  hosts: localhost
  become: no    #privilege escalation
  roles:
    - deploy-mysql

- name: Ghost configuration
  hosts: localhost
  become: no    #privilege escalation
  roles:
    - deploy-ghost

- name: Create Dashboard
  hosts: localhost
  become: no
  roles:
    - monitoring